parameters:
#    monmiel_monmiel_api_model.example.class: Monmiel\MonmielApiModelBundle\Example

services:
#    monmiel_monmiel_api_model.example:
#        class: %monmiel_monmiel_api_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
