parameters:
#    monmiel_transformers.example.class: Monmiel\TransformersBundle\Example

services:
#    monmiel_transformers.example:
#        class: %monmiel_transformers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
