<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:23:00.
 */
class AutresTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Autres
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Autres;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setPowerAutre
     * @todo   Implement testSetPowerAutre().
     */
    public function testSetPowerAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::getPowerAutre
     * @todo   Implement testGetPowerAutre().
     */
    public function testGetPowerAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setFacteurChargeAutre
     * @todo   Implement testSetFacteurChargeAutre().
     */
    public function testSetFacteurChargeAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::getFacteurChargeAutre
     * @todo   Implement testGetFacteurChargeAutre().
     */
    public function testGetFacteurChargeAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setTauxDisponibiliteAutre
     * @todo   Implement testSetTauxDisponibiliteAutre().
     */
    public function testSetTauxDisponibiliteAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::getTauxDisponibiliteAutre
     * @todo   Implement testGetTauxDisponibiliteAutre().
     */
    public function testGetTauxDisponibiliteAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::getParcAutre
     * @todo   Implement testGetParcAutre().
     */
    public function testGetParcAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
