<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:23:00.
 */
class AutresTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Autres
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Autres;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setPowerAutre
     */
    public function testSetPowerAutre()
    {
        $this->object->setPowerAutre(500);
        $exceptedValue = 500*4;
        $result = $this->object->getPowerAutre();
        assertThat($result,is($exceptedValue));
    }


    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setFacteurChargeAutre

     */
    public function testSetFacteurChargeAutre()
    {
        $this->object->setFacteurChargeAutre(0.50);
        $exceptedValue = 0.5;
        $result = $this->object->getFacteurChargeAutre();
        assertThat($result,is($exceptedValue));
    }



    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::setTauxDisponibiliteAutre

     */
    public function testSetTauxDisponibiliteAutre()
    {
        $this->object->setTauxDisponibiliteAutre(0.80);
        $exceptedValue = 0.80;
        $result = $this->object->getTauxDisponibiliteAutre();
        assertThat($result,is($exceptedValue));
    }


    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Autres::getParcAutre

     */
    public function testGetParcAutre()
    {
        $this->object->setFacteurChargeAutre(0.50);
        $this->object->setTauxDisponibiliteAutre(0.80);
        $this->object->setPowerAutre(5000);
        $exceptedValue = 62500;
        $result = intval($this->object->getParcAutre());
        assertThat($result,is($exceptedValue));
    }
}
