<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:14.
 */
class EolienTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Eolien
     */
    protected $eolien;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->eolien = new Eolien;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Eolien::setPowerEolien
     * @todo   Implement testSetPowerEolien().
     */
    public function testSetPowerEolien()
    {
        $this->eolien->setFacteurChargeEolien(75/100);
        $this->eolien->setPowerEolien(500);

        $expectedValue = 500*100/75;
        $result = $this->eolien->getPowerEolien();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Eolien::getPowerEolien
     * @todo   Implement testGetPowerEolien().
     */
    public function testGetPowerEolien()
    {
        $this->eolien->setFacteurChargeEolien(25/100);
        $this->eolien->setPowerEolien(400);

        $result = $this->eolien->getPowerEolien();

        $this->assertNotNull($result, "must not null");
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Eolien::setFacteurChargeEolien
     * @todo   Implement testSetFacteurChargeEolien().
     */
    public function testSetFacteurChargeEolien()
    {
        $this->eolien->setFacteurChargeEolien(75/100);
        $result = $this->eolien->getFacteurChargeEolien();
        $this->assertNotNull($result, "must not null");
    }

}
