<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:27.
 */
class FlammeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Flamme
     */
    protected $flamme;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->flamme = new Flamme;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setMaxFlamme
     */
    public function testSetMaxFlamme()
    {
        $this->flamme->setMaxFlamme(60000);
        $expectedValue = 60000;
        $result = $this->flamme->getMaxFlamme();
        assertThat($result, is($expectedValue));
    }


    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setFacteurChargeFlamme
     */
    public function testSetFacteurChargeFlamme()
    {
        $this->flamme->setFacteurChargeFlamme(0.75);
        $expectedValue = 0.75;
        $result = $this->flamme->getFacteurChargeFlamme();
        assertThat($result, is($expectedValue));
    }


    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setTauxDisponibiliteFlamme
     */
    public function testSetTauxDisponibiliteFlamme()
    {
        $this->flamme->setTauxDisponibiliteFlamme(0.70);
        $expectedValue = 0.70;
        $result = $this->flamme->getTauxDisponibiliteFlamme();
        assertThat($result, is($expectedValue));
    }


    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setPowerFlamme
     */
    public function testSetPowerFlamme()
    {
        $this->flamme->setMaxFlamme(3500);
        $this->flamme->setPowerFlamme();
        $this->flamme->setTauxDisponibiliteFlamme(0.70);
        $expectedValue = 3500;
        $result = $this->flamme->getPowerFlamme();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getParcFlamme
     */
    public function testGetParcFlamme()
    {
        $this->flamme->setMaxFlamme(6000);
        $this->flamme->setPowerFlamme();
        $this->flamme->setTauxDisponibiliteFlamme(0.70);
        $expectedValue = intval((6000*100/70)/500);
        $result = intval($this->flamme->getParcFlamme());
        assertThat($result, is($expectedValue));
    }
}
