<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:27.
 */
class FlammeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Flamme
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Flamme;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setMaxFlamme
     * @todo   Implement testSetMaxFlamme().
     */
    public function testSetMaxFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getMaxFlamme
     * @todo   Implement testGetMaxFlamme().
     */
    public function testGetMaxFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setFacteurChargeFlamme
     * @todo   Implement testSetFacteurChargeFlamme().
     */
    public function testSetFacteurChargeFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getFacteurChargeFlamme
     * @todo   Implement testGetFacteurChargeFlamme().
     */
    public function testGetFacteurChargeFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setTauxDisponibiliteFlamme
     * @todo   Implement testSetTauxDisponibiliteFlamme().
     */
    public function testSetTauxDisponibiliteFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getTauxDisponibiliteFlamme
     * @todo   Implement testGetTauxDisponibiliteFlamme().
     */
    public function testGetTauxDisponibiliteFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::setPowerFlamme
     * @todo   Implement testSetPowerFlamme().
     */
    public function testSetPowerFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getPowerFlamme
     * @todo   Implement testGetPowerFlamme().
     */
    public function testGetPowerFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Flamme::getParcFlamme
     * @todo   Implement testGetParcFlamme().
     */
    public function testGetParcFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
