<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-14 at 13:03:15.
 */
class GlobalParcTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GlobalParc
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $power = new \Monmiel\MonmielApiModelBundle\Model\Power(500,200,23,56231,0,789,56,23);
        $this->object = new GlobalParc($power,0.23);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::submitFlamePower
     * @todo   Implement testSubmitFlamePower().
     */
    public function testSubmitFlamePower()
    {

        $this->object->submitFlamePower(15324654.1646);
        $tmpP=$this->object->getFlamme();
        $this->assertEquals($tmpP->getPower(), 15324654.1646);

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getPower
     * @todo   Implement testGetPower().
     */
    public function testGetPower()
    {
        $flam = new Flamme(254.123);
        $hydrau = new Hydraulic(4523.987);
        $nuk = new Nuclear(712456.789);
        $pv = new Pv(145.286);
        $eol = new Eolien(456.7552);
        $this->object->setFlamme($flam);
        $this->object->setHydraulique($hydrau);
        $this->object->setNucleaire($nuk);
        $this->object->setPv($pv);
        $this->object->setEolien($eol);

        $this->assertEquals($this->object->getPower(),new \Monmiel\MonmielApiModelBundle\Model\Power(
            $flam->getPower(),
            $hydrau->getPower(),
            0,
            $nuk->getPower(),
            0,
            $pv->getPower(),
            0,
            $eol->getPower()
        ));

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::setEolien
     * @todo   Implement testSetEolien().
     */
    public function testSetEolien()
    {
       $eol = new Eolien(50.289);
       $this->object->setEolien($eol);
       $this->assertEquals($this->object->getEolien(),$eol);
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getEolien
     * @todo   Implement testGetEolien().
     */
    public function testGetEolien()
    {
       $this->assertNotNull($this->object->getEolien());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::setFlamme
     * @todo   Implement testSetFlamme().
     */
    public function testSetFlamme()
    {
        $flam = new Flamme(2356.36);
        $this->object->setFlamme($flam);
        $this->assertEquals($flam,$this->object->getFlamme());

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getFlamme
     * @todo   Implement testGetFlamme().
     */
    public function testGetFlamme()
    {
        $this->assertNotNull($this->object->getFlamme());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::setHydraulique
     * @todo   Implement testSetHydraulique().
     */
    public function testSetHydraulique()
    {
        $hydrau = new Hydraulic(523.98);
        $this->object->setHydraulique($hydrau);
        $this->assertEquals($hydrau,$this->object->getHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getHydraulique
     * @todo   Implement testGetHydraulique().
     */
    public function testGetHydraulique()
    {
        $this->assertNotNull($this->object->getHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::setNucleaire
     * @todo   Implement testSetNucleaire().
     */
    public function testSetNucleaire()
    {
        $nuk = new Nuclear(5522523.98);
        $this->object->setNucleaire($nuk);
        $this->assertEquals($nuk,$this->object->getNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getNucleaire
     * @todo   Implement testGetNucleaire().
     */
    public function testGetNucleaire()
    {
        $this->assertNotNull($this->object->getNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::setPv
     * @todo   Implement testSetPv().
     */
    public function testSetPv()
    {
        $pv = new Pv(25.569);
        $this->object->setPv($pv);
        $this->assertEquals($pv,$this->object->getPv());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\GlobalParc::getPv
     * @todo   Implement testGetPv().
     */
    public function testGetPv()
    {
        $this->assertNotNull($this->object->getPv());
    }
}
