<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:14.
 */
class ImportTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Eolien
     */
    protected $import;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->import = new Import();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @test
     */
    public function testAvalaibilityRate(){
        $this->import = new Import(0,60,0,75,5000,1);
        $this->import->setAvailabilityRate(0.60);
        $exceptedValue = 0.6;
        $result = $this->import->getAvailabilityRate();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testLoadFactor(){
        $this->import = new Import(0,60,0,75,5000,1);
        $this->import->setLoadFactor(0.75);
        $exceptedValue = 0.75;
        $result = $this->import->getLoadFactor();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testPowerUnit(){
        $this->import = new Import(0,60,0,75,5000,1);
        $this->import->setLoadFactor(0.75);
        $this->import->setAvailabilityRate(0.60);
        $exceptedValue = 1;
        $result = $this->import->getPowerUnit();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testPower(){
        $this->import = new Import(0,60,0,75,5000,1);
        $this->import->setLoadFactor(0.75);
        $this->import->setAvailabilityRate(0.60);
        $this->import->setPower(5000);
        $exceptedValue = 4000;
        $result = intval($this->import->getPower());
        assertThat($result,is($exceptedValue));
    }

}
