<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:56.
 */
class NuclearTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Nuclear
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Nuclear;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Nuclear::setPowerNuclear
     * @todo   Implement testSetPowerNuclear().
     */
    public function testSetPowerNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Nuclear::getPowerNuclear
     * @todo   Implement testGetPowerNuclear().
     */
    public function testGetPowerNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Nuclear::getFacteurChargeNuclear
     * @todo   Implement testGetFacteurChargeNuclear().
     */
    public function testGetFacteurChargeNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Nuclear::getTauxDisponibiliteNuclear
     * @todo   Implement testGetTauxDisponibiliteNuclear().
     */
    public function testGetTauxDisponibiliteNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Nuclear::getParcNuclear
     * @todo   Implement testGetParcNuclear().
     */
    public function testGetParcNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
