<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:25:21.
 */
class ParcFinalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ParcFinal
     */
    protected $finalPark;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->finalPark = new ParcFinal(5000,4000,3000,2000,1000,500);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcNucleaire

     */
    public function testGetParcNucleaire()
    {
         $this->assertNotNull($this->finalPark->getParcNucleaire());
         $expectedValue = 5000;
         $result = $this->finalPark->getParcNucleaire();
         assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcEolien
     */
    public function testGetParcEolien()
    {
        $this->assertNotNull($this->finalPark->getParcEolien());
        $expectedValue = 4000;
        $result = $this->finalPark->getParcEolien();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcPv
     */
    public function testGetParcPv()
    {
        $this->assertNotNull($this->finalPark->getParcPv());
        $expectedValue = 3000;
        $result = $this->finalPark->getParcPv();
        assertThat($result, is($expectedValue));

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcHydraulique
     */
    public function testGetParcHydraulique()
    {
        $this->assertNotNull($this->finalPark->getParcHydraulique());
        $expectedValue = 2000;
        $result = $this->finalPark->getParcHydraulique();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcFlamme
     */
    public function testGetParcFlamme()
    {
        $this->assertNotNull($this->finalPark->getParcFlamme());
        $expectedValue = 1000;
        $result = $this->finalPark->getParcFlamme();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcAutre
     */
    public function testGetParcAutre()
    {
        $this->assertNotNull($this->finalPark->getParcAutre());
        $expectedValue = 500;
        $result = $this->finalPark->getParcAutre();
        assertThat($result, is($expectedValue));
    }
}
