<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:25:21.
 */
class ParcFinalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ParcFinal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ParcFinal;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcNucleaire
     * @todo   Implement testGetParcNucleaire().
     */
    public function testGetParcNucleaire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcEolien
     * @todo   Implement testGetParcEolien().
     */
    public function testGetParcEolien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcPv
     * @todo   Implement testGetParcPv().
     */
    public function testGetParcPv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcHydraulique
     * @todo   Implement testGetParcHydraulique().
     */
    public function testGetParcHydraulique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcFlamme
     * @todo   Implement testGetParcFlamme().
     */
    public function testGetParcFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\ParcFinal::getParcAutre
     * @todo   Implement testGetParcAutre().
     */
    public function testGetParcAutre()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
