<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:25:35.
 */
class PvTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Pv
     */
    protected $pv;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->pv = new Pv;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setPowerPv
     */
    public function testSetPowerPv()
    {
      $this->pv->setFacteurChargePv(0.75);
      $this->pv->setPowerPv(400);
      $expectedValue = 400*100/75;
      $result = $this->pv->getPowerPv();
      assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setFacteurChargePv
     */
    public function testSetFacteurChargePv()
    {
        $this->pv->setFacteurChargePv(0.75);
        $expectedValue = 0.75;
        $result = $this->pv->getFacteurChargePv();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setTauxDisponibilitePv

     */
    public function testSetTauxDisponibilitePv()
    {
        $this->pv->setTauxDisponibilitePv(0.75);
        $expectedValue = 0.75;
        $result = $this->pv->getTauxDisponibilitePv();
        assertThat($result, is($expectedValue));
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::getParcPv
     */
    public function testGetParcPv()
    {
        $this->pv->setFacteurChargePv(0.75);
        $this->pv->setPowerPv(400);
        $this->pv->setTauxDisponibilitePv(0.80);
        $expectedValue = intval(((400*100/75)*100/80)/0.001);
        $result = intval($this->pv->getParcPv());
        assertThat($result, is($expectedValue));
    }
}
