<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:25:35.
 */
class PvTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Pv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Pv;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setPowerPv
     * @todo   Implement testSetPowerPv().
     */
    public function testSetPowerPv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::getPowerPv
     * @todo   Implement testGetPowerPv().
     */
    public function testGetPowerPv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setFacteurChargePv
     * @todo   Implement testSetFacteurChargePv().
     */
    public function testSetFacteurChargePv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::getFacteurChargePv
     * @todo   Implement testGetFacteurChargePv().
     */
    public function testGetFacteurChargePv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::setTauxDisponibilitePv
     * @todo   Implement testSetTauxDisponibilitePv().
     */
    public function testSetTauxDisponibilitePv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::getTauxDisponibilitePv
     * @todo   Implement testGetTauxDisponibilitePv().
     */
    public function testGetTauxDisponibilitePv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Parc\Pv::getParcPv
     * @todo   Implement testGetParcPv().
     */
    public function testGetParcPv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
