<?php
namespace Monmiel\MonmielApiModelBundle\Model\Parc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:24:56.
 */
class StepTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Step
     */
    protected $step;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->step = new Step(1,1);
    }
    /**
     * @test
     */
    public function testAvalaibilityRate(){
        $this->step = new Step(0,60,0,75,5000,1);
        $this->step->setAvailabilityRate(0.60);
        $exceptedValue = 0.6;
        $result = $this->step->getAvailabilityRate();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testLoadFactor(){
        $this->step = new Step(0,60,0,75,5000,1);
        $this->step->setLoadFactor(0.75);
        $exceptedValue = 0.75;
        $result = $this->step->getLoadFactor();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testPowerUnit(){
        $this->step = new Step(0,60,0,75,5000,1);
        $this->step->setLoadFactor(0.75);
        $this->step->setAvailabilityRate(0.60);
        $exceptedValue = 1;
        $result = $this->step->getPowerUnit();
        assertThat($result,is($exceptedValue));
    }

    /**
     * @test
     */
    public function testPower(){
        $this->step = new Step(0,60,0,75,5000,1);
        $this->step->setLoadFactor(0.75);
        $this->step->setAvailabilityRate(0.60);
        $this->step->setPower(5000);
        $exceptedValue = 4000;
        $result = intval($this->step->getPower());
        assertThat($result,is($exceptedValue));
    }

}
