<?php
namespace Monmiel\MonmielApiModelBundle\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-13 at 08:54:59.
 */
class DayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Day
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Day;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::getMax
     * @todo   Implement testGetMax().
     */
    public function testGetMax()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::addQuarters
     * @todo   Implement testAddQuarters().
     */
    public function testAddQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::getQuarter
     * @todo   Implement testGetQuarter().
     */
    public function testGetQuarter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::setDateTime
     * @todo   Implement testSetDateTime().
     */
    public function testSetDateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::getDateTime
     * @todo   Implement testGetDateTime().
     */
    public function testGetDateTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::setQuarters
     * @todo   Implement testSetQuarters().
     */
    public function testSetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Day::getQuarters
     * @todo   Implement testGetQuarters().
     */
    public function testGetQuarters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
