<?php
namespace Monmiel\MonmielApiModelBundle\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:35:14.
 */
class PowerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Power
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Power;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getTotal
     * @todo   Implement testGetTotal().
     */
    public function testGetTotal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setFlame
     * @todo   Implement testSetFlame().
     */
    public function testSetFlame()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getFlame
     * @todo   Implement testGetFlame().
     */
    public function testGetFlame()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setHydraulic
     * @todo   Implement testSetHydraulic().
     */
    public function testSetHydraulic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getHydraulic
     * @todo   Implement testGetHydraulic().
     */
    public function testGetHydraulic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setImport
     * @todo   Implement testSetImport().
     */
    public function testSetImport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getImport
     * @todo   Implement testGetImport().
     */
    public function testGetImport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setNuclear
     * @todo   Implement testSetNuclear().
     */
    public function testSetNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getNuclear
     * @todo   Implement testGetNuclear().
     */
    public function testGetNuclear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setOther
     * @todo   Implement testSetOther().
     */
    public function testSetOther()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getOther
     * @todo   Implement testGetOther().
     */
    public function testGetOther()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setPhotovoltaic
     * @todo   Implement testSetPhotovoltaic().
     */
    public function testSetPhotovoltaic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getPhotovoltaic
     * @todo   Implement testGetPhotovoltaic().
     */
    public function testGetPhotovoltaic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setStep
     * @todo   Implement testSetStep().
     */
    public function testSetStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getStep
     * @todo   Implement testGetStep().
     */
    public function testGetStep()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::setWind
     * @todo   Implement testSetWind().
     */
    public function testSetWind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Power::getWind
     * @todo   Implement testGetWind().
     */
    public function testGetWind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
