<?php
namespace Monmiel\MonmielApiModelBundle\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-13 at 08:55:20.
 */
class QuarterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Quarter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Quarter("2013-02-03",2568,123,246,256,1223,45847,456,25);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::coeffMultiplication
     * @todo   Implement testCoeffMultiplication().
     */
    public function testCoeffMultiplication()
    {
        $coeff = 0.35;
        $eolien = $this->object->getEolien();
        $hydraulique = $this->object->getHydraulique();
        $nucleaire = $this->object->getNucleaire();
        $photovoltaique = $this->object->getPhotovoltaique();
        $this->object->coeffMultiplication($coeff);
        $this->assertEquals($eolien*$coeff,$this->object->getEolien());
        $this->assertEquals($hydraulique*$coeff,$this->object->getHydraulique());
        $this->assertEquals($nucleaire*$coeff,$this->object->getNucleaire());
        $this->assertEquals($photovoltaique*$coeff,$this->object->getPhotovoltaique());

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setAutre
     * @todo   Implement testSetAutre().
     */
    public function testSetAutre()
    {
        $this->object->setAutre(123);
        $this->assertEquals(123,$this->object->getAutre());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getAutre
     * @todo   Implement testGetAutre().
     */
    public function testGetAutre()
    {
        $this->assertNotNull($this->object->getAutre());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setConsoTotal
     * @todo   Implement testSetConsoTotal().
     */
    public function testSetConsoTotal()
    {
        $this->object->setConsoTotal(55896);
        $this->assertEquals(55896,$this->object->getConsoTotal());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getConsoTotal
     * @todo   Implement testGetConsoTotal().
     */
    public function testGetConsoTotal()
    {
        $this->assertNotNull($this->object->getConsoTotal());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setDate
     * @todo   Implement testSetDate().
     */
    public function testSetDate()
    {
        $this->object->setDate('2013-03-01:01:15');
        $this->assertEquals('2013-03-01:01:15',$this->object->getDate());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getDate
     * @todo   Implement testGetDate().
     */
    public function testGetDate()
    {
        $this->assertNotNull($this->object->getDate());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setEolien
     * @todo   Implement testSetEolien().
     */
    public function testSetEolien()
    {
        $this->object->setEolien(2589);
        $this->assertEquals(2589,$this->object->getEolien());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getEolien
     * @todo   Implement testGetEolien().
     */
    public function testGetEolien()
    {
        $this->assertNotNull($this->object->getEolien());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setFlamme
     * @todo   Implement testSetFlamme().
     */
    public function testSetFlamme()
    {
        $this->object->setFlamme(5889);
        $this->assertEquals(5889,$this->object->getFlamme());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getFlamme
     * @todo   Implement testGetFlamme().
     */
    public function testGetFlamme()
    {
        $this->assertNotNull($this->object->getFlamme());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setHydraulique
     * @todo   Implement testSetHydraulique().
     */
    public function testSetHydraulique()
    {
        $this->object->setHydraulique(485526);
        $this->assertEquals(485526,$this->object->getHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getHydraulique
     * @todo   Implement testGetHydraulique().
     */
    public function testGetHydraulique()
    {
        $this->assertNotNull($this->object->getHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setNucleaire
     * @todo   Implement testSetNucleaire().
     */
    public function testSetNucleaire()
    {
        $this->object->setNucleaire(2585);
        $this->assertEquals(2585,$this->object->getNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getNucleaire
     * @todo   Implement testGetNucleaire().
     */
    public function testGetNucleaire()
    {
        $this->assertNotNull($this->object->getNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setPhotovoltaique
     * @todo   Implement testSetPhotovoltaique().
     */
    public function testSetPhotovoltaique()
    {
        $this->object->setPhotovoltaique(2569);
        $this->assertEquals(2569,$this->object->getPhotovoltaique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getPhotovoltaique
     * @todo   Implement testGetPhotovoltaique().
     */
    public function testGetPhotovoltaique()
    {
        $this->assertNotNull($this->object->getPhotovoltaique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::setSolde
     * @todo   Implement testSetSolde().
     */
    public function testSetSolde()
    {
        $this->object->setSolde(562389);
        $this->assertEquals(562389,$this->object->getSolde());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Quarter::getSolde
     * @todo   Implement testGetSolde().
     */
    public function testGetSolde()
    {
        $this->assertNotNull($this->object->getSolde());
    }
}
