<?php
namespace Monmiel\MonmielApiModelBundle\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:31:12.
 */
class YearTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Year
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Year;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalEolien
     * @todo   Implement testSetConsoTotalEolien().
     */
    public function testSetConsoTotalEolien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalEolien
     * @todo   Implement testGetConsoTotalEolien().
     */
    public function testGetConsoTotalEolien()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalHydraulique
     * @todo   Implement testSetConsoTotalHydraulique().
     */
    public function testSetConsoTotalHydraulique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalHydraulique
     * @todo   Implement testGetConsoTotalHydraulique().
     */
    public function testGetConsoTotalHydraulique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalPhotovoltaique
     * @todo   Implement testSetConsoTotalPhotovoltaique().
     */
    public function testSetConsoTotalPhotovoltaique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalPhotovoltaique
     * @todo   Implement testGetConsoTotalPhotovoltaique().
     */
    public function testGetConsoTotalPhotovoltaique()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalFlamme
     * @todo   Implement testSetConsoTotalFlamme().
     */
    public function testSetConsoTotalFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalGlobale
     * @todo   Implement testSetConsoTotalGlobale().
     */
    public function testSetConsoTotalGlobale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalFlamme
     * @todo   Implement testGetConsoTotalFlamme().
     */
    public function testGetConsoTotalFlamme()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalNucleaire
     * @todo   Implement testSetConsoTotalNucleaire().
     */
    public function testSetConsoTotalNucleaire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalNucleaire
     * @todo   Implement testGetConsoTotalNucleaire().
     */
    public function testGetConsoTotalNucleaire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setSolde
     * @todo   Implement testSetSolde().
     */
    public function testSetSolde()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getSolde
     * @todo   Implement testGetSolde().
     */
    public function testGetSolde()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalGlobale
     * @todo   Implement testGetConsoTotalGlobale().
     */
    public function testGetConsoTotalGlobale()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
