<?php
namespace Monmiel\MonmielApiModelBundle\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 15:31:12.
 */
class YearTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Year
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Year("1",256.38,569.23,245.36,8563.25,547812.36,0.365);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalEolien
     * @todo   Implement testSetConsoTotalEolien().
     */
    public function testSetConsoTotalEolien()
    {
        $this->object->setConsoTotalEolien(125.36);
        $this->assertEquals(125.36,$this->object->getConsoTotalEolien());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalEolien
     * @todo   Implement testGetConsoTotalEolien().
     */
    public function testGetConsoTotalEolien()
    {
        $this->assertNotNull($this->object->getConsoTotalEolien());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalHydraulique
     * @todo   Implement testSetConsoTotalHydraulique().
     */
    public function testSetConsoTotalHydraulique()
    {
        $this->object->setConsoTotalHydraulique(465465.39);
        $this->assertEquals(465465.39,$this->object->getConsoTotalHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalHydraulique
     * @todo   Implement testGetConsoTotalHydraulique().
     */
    public function testGetConsoTotalHydraulique()
    {
        $this->assertNotNull($this->object->getConsoTotalHydraulique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalPhotovoltaique
     * @todo   Implement testSetConsoTotalPhotovoltaique().
     */
    public function testSetConsoTotalPhotovoltaique()
    {
        $this->object->setConsoTotalPhotovoltaique(134654.25);
        $this->assertEquals(134654.25,$this->object->getConsoTotalPhotovoltaique());

    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalPhotovoltaique
     * @todo   Implement testGetConsoTotalPhotovoltaique().
     */
    public function testGetConsoTotalPhotovoltaique()
    {
        $this->assertNotNull($this->object->getConsoTotalPhotovoltaique());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalFlamme
     * @todo   Implement testSetConsoTotalFlamme().
     */
    public function testSetConsoTotalFlamme()
    {
        $this->object->setConsoTotalFlamme(1154.25);
        $this->assertEquals(1154.25,$this->object->getConsoTotalFlamme());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalGlobale
     * @todo   Implement testSetConsoTotalGlobale().
     */
    public function testSetConsoTotalGlobale()
    {
        $this->object->setConsoTotalGlobale(65649476.2589);
        $this->assertEquals(65649476.2589,$this->object->getConsoTotalGlobale());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalFlamme
     * @todo   Implement testGetConsoTotalFlamme().
     */
    public function testGetConsoTotalFlamme()
    {
        $this->assertNotNull($this->object->getConsoTotalFlamme());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setConsoTotalNucleaire
     * @todo   Implement testSetConsoTotalNucleaire().
     */
    public function testSetConsoTotalNucleaire()
    {
        $this->object->setConsoTotalNucleaire(551.2369);
        $this->assertEquals(551.2369,$this->object->getConsoTotalNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalNucleaire
     * @todo   Implement testGetConsoTotalNucleaire().
     */
    public function testGetConsoTotalNucleaire()
    {
        $this->assertNotNull($this->object->getConsoTotalNucleaire());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::setSolde
     * @todo   Implement testSetSolde().
     */
    public function testSetSolde()
    {
        $this->object->setSolde(321314654.2398);
        $this->assertEquals(321314654.2398,$this->object->getSolde());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getSolde
     * @todo   Implement testGetSolde().
     */
    public function testGetSolde()
    {
        $this->assertNotNull($this->object->getSolde());
    }

    /**
     * @covers Monmiel\MonmielApiModelBundle\Model\Year::getConsoTotalGlobale
     * @todo   Implement testGetConsoTotalGlobale().
     */
    public function testGetConsoTotalGlobale()
    {
        $this->assertNotNull($this->object->getConsoTotalGlobale());
    }
}
