parameters:
#    monmiel_mix_repartition.example.class: Monmiel\MixRepartitionBundle\Example

services:
#    monmiel_mix_repartition.example:
#        class: %monmiel_mix_repartition.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
