monmiel_api_simulation:
    pattern: /v1/{power}.json
    defaults:
        _controller: monmiel.simulation.controller:sendSimulationResult
        _format: json
    requirements:
       _method: GET

monmiel_api_test:
    pattern: /test.html
    defaults:
        _controller: monmiel.test.controller:testPerf
        _format: html
    requirements:
        _method: GET