monmiel_api_simulation:
    pattern: /v1/{targetConso}.json
    defaults:
        _controller: monmiel.simulation.controller:sendSimulationResult
        _format: json
    requirements:
       _method: GET
