parameters:
#    monmiel_monmiel_api.example.class: Monmiel\MonmielApiBundle\Example

services:
#    monmiel_monmiel_api.example:
#        class: %monmiel_monmiel_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
